site_name: covidFYI
site_description: Covid FYI
repo_url: https://github.com/tejasa97/covidFYI
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/tejasa97">tejasa97</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
