# Generated by Django 3.0.3 on 2020-04-01 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 17, 18, 56, 162704)),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=64),
        ),
    ]
