# Generated by Django 3.0.3 on 2020-04-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='source_link',
            field=models.EmailField(max_length=256, null=True),
        ),
    ]
