# Generated by Django 3.0.3 on 2020-04-01 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200401_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
